> # 幼兒園概況—按學校所在縣市別分
> 由於檔案的問題我只能使用105以及106年度的

In [7]:
import pandas as pd
import os
#read the path
cwd = os.path.abspath('')
#list all the files from the directory
csv_files = os.listdir(cwd)
csv_files

import plotly.express as px

pd.set_option("display.max_columns", None)
pd.reset_option('display.max_rows')

pd.set_option("display.max_rows", None)

In [26]:
df = pd.read_csv('105.csv',lineterminator='\n')
df.head(100)

縣市別  園數總數  公立園數  公立專設園數  分班園數  園長總數  公立  教師總數  公立教師數  教保員總數  公立教保員數  \
0   新北市  1096   245      27    58   815  26  1682   1127   4513     848   
1   臺北市   687   149      14     0   538  14  1985   1205   2228     254   
2   桃園市   528   126      15    84   386  13   967    349   2668     490   
3   臺中市   659   159      22    74   502  22  1465    620   3731     677   
4   臺南市   528   183      17    29   331  14  1150    535   2112     333   
5   高雄市   677   211      12     3   450  11  1552    803   2767     307   
6   宜蘭縣   109    56      12    20    61  10   207    140    629     305   
7   新竹縣   216    59      14    20   163  10   344    132    841     133   
8   苗栗縣   174    67      10     7   112   8   252    119    666     155   
9   彰化縣   320    72      25    59   250  17   349    155   1664     497   
10  南投縣   177    98      10    14    80   8   225    179    597     233   
11  雲林縣   140    47      20    19    90  16   193     69    810     402   
12  嘉義縣   142    84      14    15    60   5   240    154    475     215   
13  屏東縣   274   124      19    27   154  11   328    221    908     267   
14  臺東縣   117    93      14     6    32  10   210    182    224     149   
15  花蓮縣   131    85      10     7    50   5   177    114    407     232   
16  澎湖縣    23    18       4     5     8   3    38     33    102      66   
17  基隆市   102    41       3     6    60   3   203    179    317      59   
18  新竹市   161    28       1     0   132   1   416    157    584      50   
19  嘉義市    71    15       2     0    58   2   192    100    318      21   
20  金門縣    24    19       1     2     6   1    99     99     81      67   
21  連江縣     6     5       0     0     1   0    17     17      6       3   

    助理教保員總數  公立助理教保員數  服務人員總數  公立服務人員總數  職員總數  公立職員總數   幼生總數   公立幼生  年度\r  
0       504         8       0         0  2301     530  73526  22651   105  
1       157         0       0         0  1824     330  47269  17863   105  
2       311        22       0         0  1581     319  44367   9716   105  
3       475        20       0         0  1915     436  65946  14503   105  
4       272         4       0         0  1091     113  40731  10088   105  
5       275         5       0         0  1457     282  49321  11713   105  
6        75        17       0         0   347     133   9791   5039   105  
7       115         2       0         0   696     118  13997   2842   105  
8        41         3       0         0   421     112  10492   2725   105  
9       149        28       0         0   743     262  24073   7744   105  
10       48         8       0         0   362     165   9328   3970   105  
11       79        33       0         0   524     241  12818   5636   105  
12       57        20       0         0   296     117   8175   3708   105  
13       99        19       2         0   458     184  13986   5071   105  
14       19         9       0         0   219     134   4319   2790   105  
15       44        10       0         0   219     132   6561   3523   105  
16       12         8       0         0    98      63   1635   1094   105  
17       29         1       0         0   260      70   6091   2640   105  
18       85         3       0         0   407      40  11697   2352   105  
19       38         0       0         0   173      35   5918   1463   105  
20        4         0       0         0    49      44   1851   1675   105  
21        1         0       0         0     7       6    223    173   105

In [25]:
df = pd.read_csv('106.csv',lineterminator='\n')

df.head(100)

縣市別  園數總數  公立園數  公立專設園數  分班園數  園長總數  公立  教師總數  公立教師數  教保員總數  公立教保員數  \
0   新北市  1082   244      26    54   799  26  1802   1269   4534     809   
1   臺北市   682   149      14     0   528  14  1976   1234   2288     247   
2   桃園市   524   131      15    59   368  13   994    418   2730     467   
3   臺中市   664   164      22    71   494  20  1485    658   3962     677   
4   臺南市   526   184      17    28   329  15  1165    548   2197     327   
5   高雄市   669   212      12     3   437   9  1543    804   2857     327   
6   宜蘭縣   106    56      12    20    57   8   205    142    657     313   
7   新竹縣   218    62      14    17   156   8   352    144    894     141   
8   苗栗縣   173    66       9     7   106   7   247    121    660     147   
9   彰化縣   321    73      25    59   246  15   345    162   1729     506   
10  南投縣   174    99      10    13    76   8   233    190    589     226   
11  雲林縣   129    47      20    20    85  16   192     72    818     416   
12  嘉義縣   141    85      13    14    58   6   240    157    477     217   
13  屏東縣   269   125      19    27   150  13   329    226    914     264   
14  臺東縣   117    94      14    50    31  10   215    187    218     148   
15  花蓮縣   130    85      10     7    46   5   168    112    404     226   
16  澎湖縣    23    18       4     4     6   3    34     33    107      71   
17  基隆市   102    41       3     5    62   3   207    184    313      61   
18  新竹市   160    28       1     0   132   1   421    162    620      51   
19  嘉義市    71    15       2     0    56   2   192    101    322      29   
20  金門縣    24    19       1     2     6   1   109    109     86      72   
21  連江縣     5     5       0     0     0   0    23     23     11      11   

    助理教保員總數  公立助理教保員數  服務人員總數  公立服務人員總數  職員總數  公立職員總數   幼生總數   公立幼生  年度\r  
0       534         7       0         0  2426     534  77229  23618   106  
1       167         0       0         0  1821     326  50079  18412   106  
2       314        13       0         0  1618     316  47794  10273   106  
3       534        14       0         0  1933     440  72269  15226   106  
4       304         4       0         0  1092     112  43250  10444   106  
5       327         4       0         0  1486     289  54095  12336   106  
6        71        16       0         0   350     130  10247   5210   106  
7       123         1       0         0   727     117  14995   2974   106  
8        46         2       0         0   428     112  11018   2802   106  
9       159        28       0         0   769     266  25336   8203   106  
10       45         6       0         0   343     158   9873   4185   106  
11       71        23       0         0   498     232  13080   5818   106  
12       56        18       0         0   350     181   8490   3863   106  
13       92        21       2         0   461     184  14616   5298   106  
14       23         9       0         0   215     132   4510   2886   106  
15       41        10       0         0   210     130   6772   3632   106  
16       11         8       0         0    96      65   1685   1140   106  
17       33         1       0         0   268      75   6451   2856   106  
18       96         3       0         0   433      42  12544   2403   106  
19       38         0       0         0   177      34   6220   1595   106  
20        5         0       0         0    48      41   1936   1759   106  
21        0         0       0         0     9       9    292    292   106

In [27]:
df_1 = pd.concat([pd.read_csv('105.csv')])
df_2 = pd.concat([pd.read_csv('106.csv')])
df = pd.concat([df_1,df_2])
df

縣市別  園數總數  公立園數  公立專設園數  分班園數  園長總數  公立  教師總數  公立教師數  教保員總數  公立教保員數  \
0   新北市  1096   245      27    58   815  26  1682   1127   4513     848   
1   臺北市   687   149      14     0   538  14  1985   1205   2228     254   
2   桃園市   528   126      15    84   386  13   967    349   2668     490   
3   臺中市   659   159      22    74   502  22  1465    620   3731     677   
4   臺南市   528   183      17    29   331  14  1150    535   2112     333   
5   高雄市   677   211      12     3   450  11  1552    803   2767     307   
6   宜蘭縣   109    56      12    20    61  10   207    140    629     305   
7   新竹縣   216    59      14    20   163  10   344    132    841     133   
8   苗栗縣   174    67      10     7   112   8   252    119    666     155   
9   彰化縣   320    72      25    59   250  17   349    155   1664     497   
10  南投縣   177    98      10    14    80   8   225    179    597     233   
11  雲林縣   140    47      20    19    90  16   193     69    810     402   
12  嘉義縣   142    84      14    15    60   5   240    154    475     215   
13  屏東縣   274   124      19    27   154  11   328    221    908     267   
14  臺東縣   117    93      14     6    32  10   210    182    224     149   
15  花蓮縣   131    85      10     7    50   5   177    114    407     232   
16  澎湖縣    23    18       4     5     8   3    38     33    102      66   
17  基隆市   102    41       3     6    60   3   203    179    317      59   
18  新竹市   161    28       1     0   132   1   416    157    584      50   
19  嘉義市    71    15       2     0    58   2   192    100    318      21   
20  金門縣    24    19       1     2     6   1    99     99     81      67   
21  連江縣     6     5       0     0     1   0    17     17      6       3   
0   新北市  1082   244      26    54   799  26  1802   1269   4534     809   
1   臺北市   682   149      14     0   528  14  1976   1234   2288     247   
2   桃園市   524   131      15    59   368  13   994    418   2730     467   
3   臺中市   664   164      22    71   494  20  1485    658   3962     677   
4   臺南市   526   184      17    28   329  15  1165    548   2197     327   
5   高雄市   669   212      12     3   437   9  1543    804   2857     327   
6   宜蘭縣   106    56      12    20    57   8   205    142    657     313   
7   新竹縣   218    62      14    17   156   8   352    144    894     141   
8   苗栗縣   173    66       9     7   106   7   247    121    660     147   
9   彰化縣   321    73      25    59   246  15   345    162   1729     506   
10  南投縣   174    99      10    13    76   8   233    190    589     226   
11  雲林縣   129    47      20    20    85  16   192     72    818     416   
12  嘉義縣   141    85      13    14    58   6   240    157    477     217   
13  屏東縣   269   125      19    27   150  13   329    226    914     264   
14  臺東縣   117    94      14    50    31  10   215    187    218     148   
15  花蓮縣   130    85      10     7    46   5   168    112    404     226   
16  澎湖縣    23    18       4     4     6   3    34     33    107      71   
17  基隆市   102    41       3     5    62   3   207    184    313      61   
18  新竹市   160    28       1     0   132   1   421    162    620      51   
19  嘉義市    71    15       2     0    56   2   192    101    322      29   
20  金門縣    24    19       1     2     6   1   109    109     86      72   
21  連江縣     5     5       0     0     0   0    23     23     11      11   

    助理教保員總數  公立助理教保員數  服務人員總數  公立服務人員總數  職員總數  公立職員總數   幼生總數   公立幼生   年度  
0       504         8       0         0  2301     530  73526  22651  105  
1       157         0       0         0  1824     330  47269  17863  105  
2       311        22       0         0  1581     319  44367   9716  105  
3       475        20       0         0  1915     436  65946  14503  105  
4       272         4       0         0  1091     113  40731  10088  105  
5       275         5       0         0  1457     282  49321  11713  105  
6        75        17       0         0   347     133   9791   5039  105  
7       115         2       

In [48]:
total_number_per_year = df.groupby(['縣市別'])[['園數總數','幼生總數','公立幼生', ]].sum().reset_index()
total_number_per_year

縣市別  園數總數    幼生總數   公立幼生
0   南投縣   351   19201   8155
1   嘉義市   142   12138   3058
2   嘉義縣   283   16665   7571
3   基隆市   204   12542   5496
4   宜蘭縣   215   20038  10249
5   屏東縣   543   28602  10369
6   彰化縣   641   49409  15947
7   新北市  2178  150755  46269
8   新竹市   321   24241   4755
9   新竹縣   434   28992   5816
10  桃園市  1052   92161  19989
11  澎湖縣    46    3320   2234
12  臺中市  1323  138215  29729
13  臺北市  1369   97348  36275
14  臺南市  1054   83981  20532
15  臺東縣   234    8829   5676
16  花蓮縣   261   13333   7155
17  苗栗縣   347   21510   5527
18  連江縣    11     515    465
19  金門縣    48    3787   3434
20  雲林縣   269   25898  11454
21  高雄市  1346  103416  24049

In [47]:
fig = px.line(df, x="縣市別", y=["園數總數", "幼生總數","公立幼生",])
fig.show()

1. Which city had the highest number of public preschools in 106?

In [ ]:

# Read the data from the file
data = df

# Sort the data by the "公立園數" column in descending order
sorted_data = data.sort_values("公立園數", ascending=False)

# Get the city with the highest number of public preschools
city = sorted_data.iloc[0]["縣市別"]

print("The city with the highest number of public preschools is", city)


The city with the highest number of public preschools is 新北市


2. What was the total number of preschools in Yunlin County in 105?

In [ ]:
# Filter the rows for Yunlin County and select the "園數總數" column
yunlin_preschools = df[df['縣市別'] == '雲林縣']['園數總數']

# Print the total number of preschools in Yunlin County
print('Total number of preschools in Yunlin County in 105 is', yunlin_preschools.values[0])


Total number of preschools in Yunlin County in 105 is 140


3. How many preschools had specialized classes in Hualien County in 105?

In [ ]:
data = df
# Select only the rows with year 105
data = df[df['年度'] == 105]

hualien_data = df[df['縣市別'] == '花蓮縣']
specialized_count = hualien_data['公立專設園數'].sum()


print(f"Total number of specialized public preschools in Hualien County in 105 is {specialized_count}")


Total number of specialized public preschools in Hualien County in 105 is 20


4. Which county had the highest number of preschool teachers in 105?

In [ ]:

# sort the data by the "教師總數" column in descending order
sorted_df = df.sort_values("教師總數", ascending=False)

# print the county with the highest number of preschool teachers
print(sorted_df.iloc[0]["縣市別"],"has the highest number of preschool teacher.")


臺北市 has the highest number of preschool teacher.


5. What was the total number of preschool students in Taipei City in 105?

In [ ]:
data = df[df['年度'] == 105]
# filter the data to only include Taipei City
taipei_df = data[data["縣市別"] == "臺北市"]

# sum up the "幼生總數" column
total_students = taipei_df["幼生總數"].sum()

print("Total number of preschool students in Taipei City in 105 is", total_students)


Total number of preschool students in Taipei City in 105 is 47269


6. Which city had the lowest number of public preschools in 106?

In [ ]:

data = df

min_public_preschools = data['公立園數'].min()
city_with_min_public_preschools = df.loc[data['公立園數'] == min_public_preschools, '縣市別'].iloc[0]

print(city_with_min_public_preschools,"had the lowest number of public preschools in 106")


連江縣 had the lowest number of public preschools in 106


7. How many preschools had assistant teachers in Taoyuan City in 105?

In [ ]:
data = df

assistant_teachers = df.loc[data["縣市別"] == "桃園市", "助理教保員總數"].values[0]

print("The number of preschools with assistant teachers in Taoyuan City in 2016 is", assistant_teachers)


The number of preschools with assistant teachers in Taoyuan City in 2016 is 311


8. What was the total number of preschool service personnel in Tainan City in 105?

In [ ]:
data = df
# filter the dataframe to only include rows for Tainan City
tainan_df = df[data['縣市別'] == '臺南市']

# select the "服務人員總數" column and sum the values
total_service_personnel = tainan_df['服務人員總數'].sum()

print("Total number of preschool service personnel in Tainan City in 105 is", total_service_personnel)


Total number of preschool service personnel in Tainan City in 105 is 0


9. Which county had the highest number of preschool students in 105?

In [ ]:
data = df

# Group the data by county and sum the number of preschool students in each county
county_totals = data.groupby("縣市別")["幼生總數"].sum()

# Sort the data in descending order
county_totals = county_totals.sort_values(ascending=False)

# Print the county with the highest number of preschool students
print("County with highest number of preschool students in 105 is", county_totals.index[0])



County with highest number of preschool students in 105 is 新北市


10. How many preschools had public teachers in Kaohsiung City in 105?

In [ ]:
data = df
# Filter the data to only include rows where the "縣市別" column contains "高雄市"
df_kh = data[data["縣市別"].str.contains("高雄市")]

# Sum up the values in the "公立園數" column
num_public_preschools = df_kh["公立園數"].sum()

# Print the result
print(num_public_preschools,"preschools had public teachers in Kaohsiung City in 105.")


423 preschools had public teachers in Kaohsiung City in 105.
